#!/bin/bash

open -a Terminal

cat <<OSA | osascript
tell application "Terminal"
        if not (exists window 1) then reopen
        activate
        do script (quoted form of ((system attribute "PWD") & "/gh")) in window 1
end tell
OSA
